name: Deployment Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm ci
        working-directory: 02-Starting-Project
      - name: Run tests
        run: npm test
        working-directory: 02-Starting-Project
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm ci
        working-directory: 02-Starting-Project
      - name: Build project
        run: npm run build
        working-directory: 02-Starting-Project
      - name: Deploy to production
        run: |
          echo "Deploying to production server..."
          # Add your deployment commands here
        working-directory: 02-Starting-Project
