name: Output Issues Information
on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github context - issues
        run: echo "${{toJSON(github.event.issue)}}"
